[project]
    authors = [
        { name = "amane", email = "aniket_mane@sfu.ca" },
        { name = "vepain", email = "victorepain@disroot.org" },
        { name = "gdv", email = "gianluca.dellavedova@unimib.it" },
    ]
    name = "plaseval"
    version = "0.3.0"
    description = "PlasEval is a tool aimed at evaluating the accuracy and at comparing methods for the problem of plasmid binning."
    readme = "README.md"
    license = { file = "LICENSE" }
    requires-python = ">=3.13"
    dependencies = ["pandas<4.0", "bidict <1.0", "typer>=0.27.2"]

    [project.scripts]
        plaseval = "plaseval:main"

[build-system]
    requires = ["uv_build>=0.12.18,<0.13.0"]
    build-backend = "uv_build"

[dependency-groups]
    dev = [{ include-group = "stubs" }, { include-group = "test" }]
    stubs = ["pandas-stubs>=3.0.0.260204"]
    test = ["pytest>=9.1.1", "pytest-cov>=7.1.0"]

[tool.ruff.lint]
    select = ["ALL"]
    ignore = [
        # multi-line-summary-second-line
        "D213",
        # one-blank-line-before-class
        "D203",
        # flake8-todos
        "TD",
        # Fix
        "FIX",
        # missing-copyright-notice
        "CPY001",
    ]

    [tool.ruff.lint.pydocstyle]
        convention = "numpy"

    [tool.ruff.lint.extend-per-file-ignores]
        "tests/**/*.py" = [
            # at least this three should be fine in tests:
            "S101", # asserts allowed in tests...
            "ARG",  # Unused function args -> fixtures nevertheless are functionally relevant...
            "FBT",  # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
            # The below are debateable
            "PLR2004", # Magic value used in comparison, ...
            "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
            "D103",    # Missing docstring in public function
        ]

[tool.pytest]
    minversion = "9.0"
    testpaths = ["tests"]
    # addopts = "--import-mode=importlib"
    addopts = ["-ra", "-q", "--import-mode=importlib"]

[tool.coverage.run]
    source_pkgs = ["plaseval"]
    branch = true

[tool.coverage.report]
    show_missing = true
    exclude_also = [
        'def __repr__',
        'if self.debug:',
        'if settings.DEBUG',
        'raise AssertionError',
        'raise NotImplementedError',
        'if 0:',
        'if __name__ == .__main__.:',
        'if TYPE_CHECKING:',
        'class .*\bProtocol\):',
        '@(abc\.)?abstractmethod',
        "case (?:unknown|_):\\n\\s+assert_never\\(.*\\)",
    ]
